name: 'Install pnpm dependencies'
description: 'Installs pnpm dependencies and caches them.'

outputs:
  cache_key:
    description: 'The dependency cache key'
    value: ${{ steps.compute_lockfile_hash.outputs.hash }}

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.15.9

    - name: Compute dependency cache key
      id: compute_lockfile_hash
      run: node ./scripts/dependency-hash-key.js >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Check dependency cache
      uses: actions/cache@v5
      id: cache_dependencies
      with:
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: ${{ steps.compute_lockfile_hash.outputs.hash }}

    - name: Install dependencies
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash
