/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 603190983556d18d2fa32cebc898cb0b)
interface __BaseEnv_Env {
  CF_VERSION_METADATA: WorkerVersionMetadata;
  E2E_TEST_DSN: string;
  MyAgent: DurableObjectNamespace<import('./worker/index').MyAgent>;
  MyChatAgent: DurableObjectNamespace<import('./worker/index').MyChatAgent>;
  MyManualChatAgent: DurableObjectNamespace<import('./worker/index').MyManualChatAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index');
    durableNamespaces: 'MyAgent' | 'MyChatAgent' | 'MyManualChatAgent';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'E2E_TEST_DSN'>> {}
}
