name: "Install Playwright dependencies"
description: "Installs Playwright dependencies and caches them."
inputs:
  browsers:
    description: 'What browsers to install.'
    default: 'chromium webkit firefox'
  cwd:
    description: 'The working directory to run Playwright in.'
    default: '.'

runs:
  using: "composite"
  steps:
      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(node -p "require('@playwright/test/package.json').version")" >> $GITHUB_OUTPUT
        shell: bash
        working-directory: ${{ inputs.cwd }}

      # We always install all browsers
      - name: Install Playwright dependencies
        run: npx playwright install chromium webkit firefox
        shell: bash
        working-directory: ${{ inputs.cwd }}