version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma-v6
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
