version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=sentry
      - RABBITMQ_DEFAULT_PASS=sentry
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD-SHELL', 'rabbitmq-diagnostics -q ping']
      interval: 2s
      timeout: 10s
      retries: 30
      start_period: 15s

networks:
  default:
    driver: bridge
