github:
  owner: getsentry
  repo: sentry-javascript-bundler-plugins
minVersion: 2.26.3
changelogPolicy: auto
versioning:
  policy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
requireNames:
  - /^sentry-bundler-plugin-core-.*\.tgz$/
  - /^sentry-esbuild-plugin-.*\.tgz$/
  - /^sentry-rollup-plugin-.*\.tgz$/
  - /^sentry-vite-plugin-.*\.tgz$/
  - /^sentry-webpack-plugin-.*\.tgz$/
  - /^sentry-babel-plugin-component-annotate-.*\.tgz$/
targets:
  - name: github
    includeNames: /^sentry-.*.tgz$/
  - name: npm
    workspaces: true
    excludeWorkspaces: /^@sentry-internal\//
    includeWorkspaces: /^@sentry\//
