---
github:
  owner: getsentry
  repo: sentry-rrweb
changelogPolicy: none
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
    access: public
  - name: github
    tagPrefix: v
    access: public
statusProvider:
  name: github
