minVersion: '0.23.1'
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: aws-lambda-layer
    includeNames: /^sentry-node-serverless-\d+.\d+.\d+(-(beta|alpha)\.\d+)?\.zip$/
    layerName: SentryNodeServerlessSDK
    compatibleRuntimes:
      - name: node
        versions:
          - nodejs10.x
          - nodejs12.x
          - nodejs14.x
          - nodejs16.x
          - nodejs18.x
    license: MIT
  - name: gcs
    includeNames: /.*\.js.*$/
    bucket: sentry-js-sdk
    paths:
      - path: /{{version}}/
        metadata:
          cacheControl: 'public, max-age=31536000'
  - name: github
    includeNames: /^sentry-.*$/
  - name: npm
  - name: registry
    sdks:
      'npm:@sentry/browser':
        onlyIfPresent: /^sentry-browser-\d.*\.tgz$/
        includeNames: /\.js$/
        checksums:
          - algorithm: sha384
            format: base64
      'npm:@sentry/node':
        onlyIfPresent: /^sentry-node-\d.*\.tgz$/
      'npm:@sentry/react':
        onlyIfPresent: /^sentry-react-\d.*\.tgz$/
      'npm:@sentry/vue':
        onlyIfPresent: /^sentry-vue-\d.*\.tgz$/
      'npm:@sentry/gatsby':
        onlyIfPresent: /^sentry-gatsby-\d.*\.tgz$/
      'npm:@sentry/angular-ivy':
        onlyIfPresent: /^sentry-angular-ivy-\d.*\.tgz$/
      'npm:@sentry/angular':
        onlyIfPresent: /^sentry-angular-\d.*\.tgz$/
      'npm:@sentry/wasm':
        onlyIfPresent: /^sentry-wasm-\d.*\.tgz$/
      'npm:@sentry/nextjs':
        onlyIfPresent: /^sentry-nextjs-\d.*\.tgz$/
      'npm:@sentry/remix':
        onlyIfPresent: /^sentry-remix-\d.*\.tgz$/
      'npm:@sentry/svelte':
        onlyIfPresent: /^sentry-svelte-\d.*\.tgz$/
      'npm:@sentry/sveltekit':
        onlyIfPresent: /^sentry-sveltekit-\d.*\.tgz$/
      'npm:@sentry/opentelemetry-node':
        onlyIfPresent: /^sentry-opentelemetry-node-\d.*\.tgz$/
