minVersion: '0.6.0'
github:
  owner: getsentry
  repo: sentry-javascript
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
    includeNames: /^sentry-.*$/
  - name: gcs
    includeNames: /^bundle\..*$/
    bucket: sentry-js-sdk
    paths:
      - path: /{{version}}/
        metadata:
          cacheControl: 'public, max-age=31536000'
  - name: registry
    type: sdk
    includeNames: /^sentry-browser-.*\.tgz$/
    config:
      canonical: 'npm:@sentry/browser'
  - name: registry
    type: sdk
    includeNames: /^sentry-node-.*\.tgz$/
    config:
      canonical: 'npm:@sentry/node'
  - name: gh-pages
