comment: off
codecov:
  notify:
    require_ci_to_pass: no

ai_pr_review:
  enabled: true
  method: 'label'
  label_name: 'ci-codecov-ai-review'

coverage:
  precision: 2
  round: down
  range: '0...1'
  status:
    project:
      default:
        enabled: no
    patch:
      default:
        enabled: no
