comment: off
codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: '0...1'
  status:
    project: false
    patch:
      default:
        enabled: no

ignore:
  - 'packages/deno/**'
