comment: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
  ignore:
    - 'packages/deno/**'

config:
  files: changed
