packages:
  - 'packages/angular'
  - 'packages/astro'
  - 'packages/aws-serverless'
  - 'packages/browser'
  - 'packages/browser-utils'
  - 'packages/bun'
  - 'packages/core'
  - 'packages/cloudflare'
  - 'packages/deno'
  - 'packages/effect'
  - 'packages/ember'
  - 'packages/elysia'
  - 'packages/eslint-config-sdk'
  - 'packages/eslint-plugin-sdk'
  - 'packages/feedback'
  - 'packages/gatsby'
  - 'packages/google-cloud-serverless'
  - 'packages/hono'
  - 'packages/integration-shims'
  - 'packages/nestjs'
  - 'packages/nextjs'
  - 'packages/node'
  - 'packages/node-core'
  - 'packages/node-native'
  - 'packages/nuxt'
  - 'packages/opentelemetry'
  - 'packages/profiling-node'
  - 'packages/react'
  - 'packages/react-router'
  - 'packages/remix'
  - 'packages/replay-internal'
  - 'packages/replay-canvas'
  - 'packages/replay-worker'
  - 'packages/solid'
  - 'packages/solidstart'
  - 'packages/svelte'
  - 'packages/sveltekit'
  - 'packages/tanstackstart'
  - 'packages/tanstackstart-react'
  - 'packages/types'
  - 'packages/typescript'
  - 'packages/vercel-edge'
  - 'packages/vue'
  - 'packages/wasm'
  - 'dev-packages/browser-integration-tests'
  - 'dev-packages/bundle-analyzer-scenarios'
  - 'dev-packages/e2e-tests'
  - 'dev-packages/node-integration-tests'
  - 'dev-packages/cloudflare-integration-tests'
  - 'dev-packages/node-core-integration-tests'
  - 'dev-packages/test-utils'
  - 'dev-packages/size-limit-gh-action'
  - 'dev-packages/clear-cache-gh-action'
  - 'dev-packages/external-contributor-gh-action'
  - 'dev-packages/rollup-utils'
  - 'dev-packages/node-overhead-gh-action'
  - 'dev-packages/bundler-tests'
