name: 'release-comment-issues-gh-action'
description: 'An internal Github Action to comment on related issues when a release is published.'
inputs:
  github_token:
    required: true
    description: 'a github access token'
  version:
    required: true
    description: 'Which version was released'
runs:
  using: 'node20'
  main: 'index.mjs'
