import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';
import { sentryPagesPlugin } from '@sentry/cloudflare';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from '../build/server';

export const onRequest = [
  (context: EventPluginContext<any, any, any, any>) =>
    sentryPagesPlugin({
      dsn: context.env.E2E_TEST_DSN,
      tracesSampleRate: 1.0,
    })(context),
  createPagesFunctionHandler({ build }),
];
