/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as TestServerFnRouteImport } from './routes/test-serverFn';
import { Route as TestMiddlewareRouteImport } from './routes/test-middleware';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ApiTestMiddlewareRouteImport } from './routes/api.test-middleware';
import { Route as ApiErrorRouteImport } from './routes/api.error';

const TestServerFnRoute = TestServerFnRouteImport.update({
  id: '/test-serverFn',
  path: '/test-serverFn',
  getParentRoute: () => rootRouteImport,
} as any);
const TestMiddlewareRoute = TestMiddlewareRouteImport.update({
  id: '/test-middleware',
  path: '/test-middleware',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiTestMiddlewareRoute = ApiTestMiddlewareRouteImport.update({
  id: '/api/test-middleware',
  path: '/api/test-middleware',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiErrorRoute = ApiErrorRouteImport.update({
  id: '/api/error',
  path: '/api/error',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/test-middleware': typeof TestMiddlewareRoute;
  '/test-serverFn': typeof TestServerFnRoute;
  '/api/error': typeof ApiErrorRoute;
  '/api/test-middleware': typeof ApiTestMiddlewareRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/test-middleware': typeof TestMiddlewareRoute;
  '/test-serverFn': typeof TestServerFnRoute;
  '/api/error': typeof ApiErrorRoute;
  '/api/test-middleware': typeof ApiTestMiddlewareRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/test-middleware': typeof TestMiddlewareRoute;
  '/test-serverFn': typeof TestServerFnRoute;
  '/api/error': typeof ApiErrorRoute;
  '/api/test-middleware': typeof ApiTestMiddlewareRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/test-middleware' | '/test-serverFn' | '/api/error' | '/api/test-middleware';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/test-middleware' | '/test-serverFn' | '/api/error' | '/api/test-middleware';
  id: '__root__' | '/' | '/test-middleware' | '/test-serverFn' | '/api/error' | '/api/test-middleware';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  TestMiddlewareRoute: typeof TestMiddlewareRoute;
  TestServerFnRoute: typeof TestServerFnRoute;
  ApiErrorRoute: typeof ApiErrorRoute;
  ApiTestMiddlewareRoute: typeof ApiTestMiddlewareRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-serverFn': {
      id: '/test-serverFn';
      path: '/test-serverFn';
      fullPath: '/test-serverFn';
      preLoaderRoute: typeof TestServerFnRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/test-middleware': {
      id: '/test-middleware';
      path: '/test-middleware';
      fullPath: '/test-middleware';
      preLoaderRoute: typeof TestMiddlewareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/test-middleware': {
      id: '/api/test-middleware';
      path: '/api/test-middleware';
      fullPath: '/api/test-middleware';
      preLoaderRoute: typeof ApiTestMiddlewareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/error': {
      id: '/api/error';
      path: '/api/error';
      fullPath: '/api/error';
      preLoaderRoute: typeof ApiErrorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestMiddlewareRoute: TestMiddlewareRoute,
  TestServerFnRoute: TestServerFnRoute,
  ApiErrorRoute: ApiErrorRoute,
  ApiTestMiddlewareRoute: ApiTestMiddlewareRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
