export type { Carrier, Layer } from '@sentry/core';

export {
  getCurrentHub,
  addGlobalEventProcessor,
  Scope,
  getHubFromCarrier,
  getMainCarrier,
  Hub,
  makeMain,
  setHubOnCarrier,
  SessionFlusher,
  closeSession,
  makeSession,
  updateSession,
  addBreadcrumb,
  captureException,
  captureEvent,
  captureMessage,
  configureScope,
  startTransaction,
  setContext,
  setExtra,
  setExtras,
  setTag,
  setTags,
  setUser,
  withScope,
} from '@sentry/core';
