version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-postgresjs
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test -d test_db']
      interval: 500ms
      timeout: 3s
      retries: 60
      start_period: 2s

  ready-gate:
    image: busybox
    depends_on:
      db:
        condition: service_healthy
    command: ['echo', 'postgresjs-ready']
