export {
  addEventProcessor,
  addBreadcrumb,
  addIntegration,
  captureException,
  captureEvent,
  captureMessage,
  captureCheckIn,
  captureFeedback,
  startSession,
  captureSession,
  endSession,
  withMonitor,
  createTransport,
  getClient,
  isInitialized,
  isEnabled,
  getCurrentScope,
  getGlobalScope,
  getIsolationScope,
  getTraceData,
  getTraceMetaTags,
  setCurrentClient,
  Scope,
  SDK_VERSION,
  setContext,
  setConversationId,
  setExtra,
  setExtras,
  setTag,
  setTags,
  setAttribute,
  setAttributes,
  setUser,
  getSpanStatusFromHttpCode,
  setHttpStatus,
  withScope,
  withIsolationScope,
  makeNodeTransport,
  NodeClient,
  defaultStackParser,
  lastEventId,
  flush,
  close,
  getSentryRelease,
  createGetModuleFromFilename,
  createLangChainCallbackHandler,
  instrumentLangChainEmbeddings,
  httpHeadersToSpanAttributes,
  winterCGHeadersToDict,
  // eslint-disable-next-line typescript/no-deprecated
  anrIntegration,
  // eslint-disable-next-line typescript/no-deprecated
  disableAnrDetectionForCallback,
  consoleIntegration,
  httpIntegration,
  httpServerIntegration,
  httpServerSpansIntegration,
  nativeNodeFetchIntegration,
  onUncaughtExceptionIntegration,
  onUnhandledRejectionIntegration,
  openAIIntegration,
  langChainIntegration,
  langGraphIntegration,
  modulesIntegration,
  nodeRuntimeMetricsIntegration,
  type NodeRuntimeMetricsOptions,
  contextLinesIntegration,
  nodeContextIntegration,
  localVariablesIntegration,
  requestDataIntegration,
  functionToStringIntegration,
  eventFiltersIntegration,
  linkedErrorsIntegration,
  setMeasurement,
  getActiveSpan,
  startSpan,
  startInactiveSpan,
  startSpanManual,
  startNewTrace,
  bindScopeToEmitter,
  suppressTracing,
  withActiveSpan,
  getRootSpan,
  getSpanDescendants,
  continueTrace,
  getAutoPerformanceIntegrations,
  cron,
  parameterize,
  SEMANTIC_ATTRIBUTE_SENTRY_OP,
  SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN,
  SEMANTIC_ATTRIBUTE_SENTRY_SOURCE,
  SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE,
  dataloaderIntegration,
  expressIntegration,
  expressErrorHandler,
  setupExpressErrorHandler,
  koaIntegration,
  setupKoaErrorHandler,
  fastifyIntegration,
  firebaseIntegration,
  fsIntegration,
  genericPoolIntegration,
  graphqlIntegration,
  knexIntegration,
  kafkaIntegration,
  lruMemoizerIntegration,
  mongoIntegration,
  mongooseIntegration,
  mysqlIntegration,
  mysql2Integration,
  redisIntegration,
  tediousIntegration,
  pinoIntegration,
  postgresIntegration,
  postgresJsIntegration,
  processSessionIntegration,
  prismaIntegration,
  otlpIntegration,
  getOtlpTracesEndpoint,
  childProcessIntegration,
  createSentryWinstonTransport,
  hapiIntegration,
  setupHapiErrorHandler,
  spotlightIntegration,
  initOpenTelemetry,
  spanToStaticSpanJSON,
  spanToJSON,
  spanToTraceHeader,
  spanToBaggageHeader,
  systemErrorIntegration,
  trpcMiddleware,
  updateSpanName,
  supabaseIntegration,
  instrumentSupabaseClient,
  instrumentOpenAiClient,
  instrumentAnthropicAiClient,
  instrumentGoogleGenAIClient,
  instrumentStateGraph,
  instrumentStateGraphCompile,
  zodErrorsIntegration,
  profiler,
  amqplibIntegration,
  anthropicAIIntegration,
  googleGenAIIntegration,
  vercelAIIntegration,
  logger,
  consoleLoggingIntegration,
  createConsolaReporter,
  wrapMcpServerWithSentry,
  NODE_VERSION,
  featureFlagsIntegration,
  type FeatureFlagsIntegration,
  launchDarklyIntegration,
  buildLaunchDarklyFlagUsedHandler,
  openFeatureIntegration,
  OpenFeatureIntegrationHook,
  statsigIntegration,
  unleashIntegration,
  growthbookIntegration,
  metrics,
  spanStreamingIntegration,
  withStaticSpan,
  // oxlint-disable-next-line typescript/no-deprecated
  withStreamedSpan,
} from '@sentry/node';

export {
  captureConsoleIntegration,
  dedupeIntegration,
  extraErrorDataIntegration,
  rewriteFramesIntegration,
} from '@sentry/core';

export { awsIntegration } from '@sentry/server-utils/orchestrion';
export { awsLambdaIntegration } from './integration/awslambda';

export { getDefaultIntegrations, init } from './init';
// eslint-disable-next-line typescript/no-deprecated
export { wrapHandler } from './sdk';
export type { WrapperOptions } from './sdk';
