import { afterAll, describe, expect } from 'vitest';
import { cleanupChildProcesses, createEsmAndCjsTests } from '../../../utils/runner';

// `ai` SDK only support Node 18+
describe('Vercel AI integration', () => {
  afterAll(() => {
    cleanupChildProcesses();
  });

  const EXPECTED_TRANSACTION_DEFAULT_PII_FALSE = {
    transaction: 'main',
    spans: expect.arrayContaining([
      // First span - no telemetry config, should enable telemetry but not record inputs/outputs when sendDefaultPii: false
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText',
          'ai.pipeline.name': 'generateText',
          'ai.response.finishReason': 'stop',
          'ai.settings.maxRetries': 2,
          'ai.settings.maxSteps': 1,
          'ai.streaming': false,
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.input_tokens': 10,
          'gen_ai.usage.output_tokens': 20,
          'gen_ai.usage.total_tokens': 30,
          'operation.name': 'ai.generateText',
          'sentry.op': 'ai.pipeline.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generateText',
        op: 'ai.pipeline.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Second span - explicitly enabled telemetry but recordInputs/recordOutputs not set, should not record when sendDefaultPii: false
      expect.objectContaining({
        data: {
          'sentry.origin': 'auto.vercelai.otel',
          'sentry.op': 'gen_ai.generate_text',
          'operation.name': 'ai.generateText.doGenerate',
          'ai.operationId': 'ai.generateText.doGenerate',
          'ai.model.provider': 'mock-provider',
          'ai.model.id': 'mock-model-id',
          'ai.settings.maxRetries': 2,
          'gen_ai.system': 'mock-provider',
          'gen_ai.request.model': 'mock-model-id',
          'ai.pipeline.name': 'generateText.doGenerate',
          'ai.streaming': false,
          'ai.response.finishReason': 'stop',
          'ai.response.model': 'mock-model-id',
          'ai.response.id': expect.any(String),
          'ai.response.timestamp': expect.any(String),
          'gen_ai.response.finish_reasons': ['stop'],
          'gen_ai.usage.input_tokens': 10,
          'gen_ai.usage.output_tokens': 20,
          'gen_ai.response.id': expect.any(String),
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.total_tokens': 30,
        },
        description: 'generate_text mock-model-id',
        op: 'gen_ai.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Third span - explicit telemetry enabled, should record inputs/outputs regardless of sendDefaultPii
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText',
          'ai.pipeline.name': 'generateText',
          'ai.prompt': '{"prompt":"Where is the second span?"}',
          'ai.response.finishReason': 'stop',
          'gen_ai.response.text': expect.any(String),
          'ai.settings.maxRetries': 2,
          'ai.settings.maxSteps': 1,
          'ai.streaming': false,
          'gen_ai.prompt': '{"prompt":"Where is the second span?"}',
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.input_tokens': 10,
          'gen_ai.usage.output_tokens': 20,
          'gen_ai.usage.total_tokens': 30,
          'operation.name': 'ai.generateText',
          'sentry.op': 'ai.pipeline.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generateText',
        op: 'ai.pipeline.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Fourth span - doGenerate for explicit telemetry enabled call
      expect.objectContaining({
        data: {
          'sentry.origin': 'auto.vercelai.otel',
          'sentry.op': 'gen_ai.generate_text',
          'operation.name': 'ai.generateText.doGenerate',
          'ai.operationId': 'ai.generateText.doGenerate',
          'ai.model.provider': 'mock-provider',
          'ai.model.id': 'mock-model-id',
          'ai.settings.maxRetries': 2,
          'gen_ai.system': 'mock-provider',
          'gen_ai.request.model': 'mock-model-id',
          'ai.pipeline.name': 'generateText.doGenerate',
          'ai.streaming': false,
          'ai.response.finishReason': 'stop',
          'ai.response.model': 'mock-model-id',
          'ai.response.id': expect.any(String),
          'gen_ai.response.text': expect.any(String),
          'ai.response.timestamp': expect.any(String),
          'ai.prompt.format': expect.any(String),
          'gen_ai.request.messages': expect.any(String),
          'gen_ai.response.finish_reasons': ['stop'],
          'gen_ai.usage.input_tokens': 10,
          'gen_ai.usage.output_tokens': 20,
          'gen_ai.response.id': expect.any(String),
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.total_tokens': 30,
        },
        description: 'generate_text mock-model-id',
        op: 'gen_ai.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Fifth span - tool call generateText span
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText',
          'ai.pipeline.name': 'generateText',
          'ai.response.finishReason': 'tool-calls',
          'ai.settings.maxRetries': 2,
          'ai.settings.maxSteps': 1,
          'ai.streaming': false,
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.input_tokens': 15,
          'gen_ai.usage.output_tokens': 25,
          'gen_ai.usage.total_tokens': 40,
          'operation.name': 'ai.generateText',
          'sentry.op': 'ai.pipeline.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generateText',
        op: 'ai.pipeline.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Sixth span - tool call doGenerate span
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText.doGenerate',
          'ai.pipeline.name': 'generateText.doGenerate',
          'ai.response.finishReason': 'tool-calls',
          'ai.response.id': expect.any(String),
          'ai.response.model': 'mock-model-id',
          'ai.response.timestamp': expect.any(String),
          'ai.settings.maxRetries': 2,
          'ai.streaming': false,
          'gen_ai.request.model': 'mock-model-id',
          'gen_ai.response.finish_reasons': ['tool-calls'],
          'gen_ai.response.id': expect.any(String),
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.system': 'mock-provider',
          'gen_ai.usage.input_tokens': 15,
          'gen_ai.usage.output_tokens': 25,
          'gen_ai.usage.total_tokens': 40,
          'operation.name': 'ai.generateText.doGenerate',
          'sentry.op': 'gen_ai.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generate_text mock-model-id',
        op: 'gen_ai.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Seventh span - tool call execution span
      expect.objectContaining({
        data: {
          'ai.operationId': 'ai.toolCall',
          'ai.toolCall.id': 'call-1',
          'ai.toolCall.name': 'getWeather',
          'gen_ai.tool.call.id': 'call-1',
          'gen_ai.tool.name': 'getWeather',
          'operation.name': 'ai.toolCall',
          'sentry.op': 'gen_ai.execute_tool',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'execute_tool getWeather',
        op: 'gen_ai.execute_tool',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
    ]),
  };

  const EXPECTED_TRANSACTION_DEFAULT_PII_TRUE = {
    transaction: 'main',
    spans: expect.arrayContaining([
      // First span - no telemetry config, should enable telemetry AND record inputs/outputs when sendDefaultPii: true
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText',
          'ai.pipeline.name': 'generateText',
          'ai.prompt': '{"prompt":"Where is the first span?"}',
          'ai.response.finishReason': 'stop',
          'gen_ai.response.text': 'First span here!',
          'ai.settings.maxRetries': 2,
          'ai.settings.maxSteps': 1,
          'ai.streaming': false,
          'gen_ai.prompt': '{"prompt":"Where is the first span?"}',
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.input_tokens': 10,
          'gen_ai.usage.output_tokens': 20,
          'gen_ai.usage.total_tokens': 30,
          'operation.name': 'ai.generateText',
          'sentry.op': 'ai.pipeline.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generateText',
        op: 'ai.pipeline.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Second span - doGenerate for first call, should also include input/output fields when sendDefaultPii: true
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText.doGenerate',
          'ai.pipeline.name': 'generateText.doGenerate',
          'ai.prompt.format': 'prompt',
          'gen_ai.request.messages': '[{"role":"user","content":[{"type":"text","text":"Where is the first span?"}]}]',
          'ai.response.finishReason': 'stop',
          'ai.response.id': expect.any(String),
          'ai.response.model': 'mock-model-id',
          'gen_ai.response.text': 'First span here!',
          'ai.response.timestamp': expect.any(String),
          'ai.settings.maxRetries': 2,
          'ai.streaming': false,
          'gen_ai.request.model': 'mock-model-id',
          'gen_ai.response.finish_reasons': ['stop'],
          'gen_ai.response.id': expect.any(String),
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.system': 'mock-provider',
          'gen_ai.usage.input_tokens': 10,
          'gen_ai.usage.output_tokens': 20,
          'gen_ai.usage.total_tokens': 30,
          'operation.name': 'ai.generateText.doGenerate',
          'sentry.op': 'gen_ai.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generate_text mock-model-id',
        op: 'gen_ai.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Third span - explicitly enabled telemetry, should record inputs/outputs regardless of sendDefaultPii
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText',
          'ai.pipeline.name': 'generateText',
          'ai.prompt': '{"prompt":"Where is the second span?"}',
          'ai.response.finishReason': 'stop',
          'gen_ai.response.text': expect.any(String),
          'ai.settings.maxRetries': 2,
          'ai.settings.maxSteps': 1,
          'ai.streaming': false,
          'gen_ai.prompt': '{"prompt":"Where is the second span?"}',
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.input_tokens': 10,
          'gen_ai.usage.output_tokens': 20,
          'gen_ai.usage.total_tokens': 30,
          'operation.name': 'ai.generateText',
          'sentry.op': 'ai.pipeline.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generateText',
        op: 'ai.pipeline.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Fourth span - doGenerate for explicitly enabled telemetry call
      expect.objectContaining({
        data: {
          'sentry.origin': 'auto.vercelai.otel',
          'sentry.op': 'gen_ai.generate_text',
          'operation.name': 'ai.generateText.doGenerate',
          'ai.operationId': 'ai.generateText.doGenerate',
          'ai.model.provider': 'mock-provider',
          'ai.model.id': 'mock-model-id',
          'ai.settings.maxRetries': 2,
          'gen_ai.system': 'mock-provider',
          'gen_ai.request.model': 'mock-model-id',
          'ai.pipeline.name': 'generateText.doGenerate',
          'ai.streaming': false,
          'ai.response.finishReason': 'stop',
          'ai.response.model': 'mock-model-id',
          'ai.response.id': expect.any(String),
          'gen_ai.response.text': expect.any(String),
          'ai.response.timestamp': expect.any(String),
          'ai.prompt.format': expect.any(String),
          'gen_ai.request.messages': expect.any(String),
          'gen_ai.response.finish_reasons': ['stop'],
          'gen_ai.usage.input_tokens': 10,
          'gen_ai.usage.output_tokens': 20,
          'gen_ai.response.id': expect.any(String),
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.total_tokens': 30,
        },
        description: 'generate_text mock-model-id',
        op: 'gen_ai.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Fifth span - tool call generateText span (should include prompts when sendDefaultPii: true)
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText',
          'ai.pipeline.name': 'generateText',
          'ai.prompt': '{"prompt":"What is the weather in San Francisco?"}',
          'ai.response.finishReason': 'tool-calls',
          'gen_ai.response.text': 'Tool call completed!',
          'gen_ai.response.tool_calls': expect.any(String),
          'ai.settings.maxRetries': 2,
          'ai.settings.maxSteps': 1,
          'ai.streaming': false,
          'gen_ai.prompt': '{"prompt":"What is the weather in San Francisco?"}',
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.usage.input_tokens': 15,
          'gen_ai.usage.output_tokens': 25,
          'gen_ai.usage.total_tokens': 40,
          'operation.name': 'ai.generateText',
          'sentry.op': 'ai.pipeline.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generateText',
        op: 'ai.pipeline.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Sixth span - tool call doGenerate span (should include prompts when sendDefaultPii: true)
      expect.objectContaining({
        data: {
          'ai.model.id': 'mock-model-id',
          'ai.model.provider': 'mock-provider',
          'ai.operationId': 'ai.generateText.doGenerate',
          'ai.pipeline.name': 'generateText.doGenerate',
          'ai.prompt.format': expect.any(String),
          'gen_ai.request.messages': expect.any(String),
          'ai.prompt.toolChoice': expect.any(String),
          'gen_ai.request.available_tools': expect.any(Array),
          'ai.response.finishReason': 'tool-calls',
          'ai.response.id': expect.any(String),
          'ai.response.model': 'mock-model-id',
          'gen_ai.response.text': 'Tool call completed!',
          'ai.response.timestamp': expect.any(String),
          'gen_ai.response.tool_calls': expect.any(String),
          'ai.settings.maxRetries': 2,
          'ai.streaming': false,
          'gen_ai.request.model': 'mock-model-id',
          'gen_ai.response.finish_reasons': ['tool-calls'],
          'gen_ai.response.id': expect.any(String),
          'gen_ai.response.model': 'mock-model-id',
          'gen_ai.system': 'mock-provider',
          'gen_ai.usage.input_tokens': 15,
          'gen_ai.usage.output_tokens': 25,
          'gen_ai.usage.total_tokens': 40,
          'operation.name': 'ai.generateText.doGenerate',
          'sentry.op': 'gen_ai.generate_text',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'generate_text mock-model-id',
        op: 'gen_ai.generate_text',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
      // Seventh span - tool call execution span
      expect.objectContaining({
        data: {
          'ai.operationId': 'ai.toolCall',
          'ai.toolCall.args': expect.any(String),
          'ai.toolCall.id': 'call-1',
          'ai.toolCall.name': 'getWeather',
          'ai.toolCall.result': expect.any(String),
          'gen_ai.tool.call.id': 'call-1',
          'gen_ai.tool.name': 'getWeather',
          'operation.name': 'ai.toolCall',
          'sentry.op': 'gen_ai.execute_tool',
          'sentry.origin': 'auto.vercelai.otel',
        },
        description: 'execute_tool getWeather',
        op: 'gen_ai.execute_tool',
        origin: 'auto.vercelai.otel',
        status: 'ok',
      }),
    ]),
  };

  createEsmAndCjsTests(__dirname, 'scenario.mjs', 'instrument.mjs', (createRunner, test) => {
    test('creates ai related spans with sendDefaultPii: false', async () => {
      await createRunner().expect({ transaction: EXPECTED_TRANSACTION_DEFAULT_PII_FALSE }).start().completed();
    });
  });

  createEsmAndCjsTests(__dirname, 'scenario.mjs', 'instrument-with-pii.mjs', (createRunner, test) => {
    test('creates ai related spans with sendDefaultPii: true', async () => {
      await createRunner().expect({ transaction: EXPECTED_TRANSACTION_DEFAULT_PII_TRUE }).start().completed();
    });
  });
});
