version: '3.9'

services:
  db_postgres:
    image: postgres:13
    restart: always
    container_name: integration-tests-knex-postgres
    ports:
      - '5445:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: tests

  db_mysql2:
    image: mysql:8
    restart: always
    container_name: integration-tests-knex-mysql2
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: tests
