import * as childProcess from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Run the given shell command, piping the shell process's `stdin`, `stdout`, and `stderr` to that of the current
 * process. Returns contents of `stdout`.
 */
function run(cmd: string, options?: childProcess.ExecSyncOptions): string | Buffer {
  return childProcess.execSync(cmd, { stdio: 'inherit', ...options });
}

run('yarn rolldown -c rollup.npm.config.mjs');

// Regardless of whether nextjs is using the CJS or ESM version of our SDK, we want the code from our templates to be in
// ESM (since we'll be adding it onto page files which are themselves written in ESM), so copy the ESM versions of the
// templates over into the CJS build directory. (Building only the ESM version and sticking it in both locations is
// something which in theory Rollup could do, but it would mean refactoring our Rollup helper functions, which isn't
// worth it just for this.)
const cjsTemplateDir = 'build/cjs/config/templates/';
const esmTemplateDir = 'build/esm/config/templates/';
fs.readdirSync(esmTemplateDir).forEach(templateFile =>
  fs.copyFileSync(path.join(esmTemplateDir, templateFile), path.join(cjsTemplateDir, templateFile)),
);

// Generate the orchestrion runtime forwarders (see `src/config/diagnosticsChannelInjection.ts`)
// from `@sentry/server-utils`' own exports map, so a new subpath there is forwarded automatically.
// Only `require`-able entries get one, since the emitted external is a `require()`. Written as
// plain CJS, not built by rollup: they are loaded by specifier, never bundled.
const SERVER_UTILS = '@sentry/server-utils';
const orchestrionRuntimeBuildDir = 'build/orchestrion-runtime';

const serverUtilsExports = (
  JSON.parse(fs.readFileSync(require.resolve(`${SERVER_UTILS}/package.json`), 'utf8')) as {
    exports: Record<string, { require?: string } | string>;
  }
).exports;

for (const [key, conditions] of Object.entries(serverUtilsExports)) {
  if (key === './package.json' || typeof conditions === 'string' || !conditions.require) {
    continue;
  }

  // '.' → 'index', './orchestrion/register' → 'orchestrion/register'
  const forwarderPath = path.join(orchestrionRuntimeBuildDir, `${key === '.' ? 'index' : key.slice(2)}.js`);
  fs.mkdirSync(path.dirname(forwarderPath), { recursive: true });
  fs.writeFileSync(
    forwarderPath,
    `// Generated by scripts/buildRollup.ts — do not edit.\nmodule.exports = require('${SERVER_UTILS}${key.slice(1)}');\n`,
  );
}
