version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: integration-tests-tedious
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'TESTing123'
