/**
 * Browser APIs re-exported from `@sentry/react`.
 *
 * This is intentionally a **curated** surface rather than `export * from '@sentry/browser'`.
 *
 * Why: bundlers that treat a dynamic `import('@sentry/react')` namespace as using every
 * export (Rolldown when the namespace is destructured) would otherwise pull optional
 * `@sentry/browser` features into the critical path — Replay (~265KB), Feedback, AI
 * instrumenters, feature-flag integrations, etc. — even when the app never references them.
 *
 * Optional features remain available from `@sentry/browser` (full entry),
 * `@sentry/react/optional-browser-api`, or dedicated packages (`@sentry/replay`, …).
 *
 * Everything here is re-exported from `@sentry/browser/core` so this module never
 * links the full browser barrel.
 */

export type {
  Breadcrumb,
  BreadcrumbHint,
  BrowserOptions,
  CaptureContext,
  Context,
  Contexts,
  ErrorEvent,
  Event,
  EventHint,
  Exception,
  ExclusiveEventHintOrCaptureContext,
  Log,
  LogSeverityLevel,
  ReportDialogOptions,
  RequestEventData,
  RequestInstrumentationOptions,
  SdkInfo,
  Session,
  SeverityLevel,
  Span,
  StackFrame,
  Stacktrace,
  Thread,
  User,
} from '@sentry/browser/core';

export {
  // Core client / scope APIs
  addBreadcrumb,
  addEventProcessor,
  addIntegration,
  BrowserClient,
  captureEvent,
  captureException,
  captureFeedback,
  captureMessage,
  captureSession,
  close,
  continueTrace,
  createTransport,
  createUserFeedbackEnvelope,
  endSession,
  eventFromException,
  eventFromMessage,
  exceptionFromError,
  flush,
  forceLoad,
  getClient,
  getCurrentScope,
  getDefaultIntegrations,
  getGlobalScope,
  getIsolationScope,
  getTraceData,
  isEnabled,
  isInitialized,
  lastEventId,
  // eslint-disable-next-line typescript/no-deprecated
  inboundFiltersIntegration,
  eventFiltersIntegration,
  functionToStringIntegration,
  dedupeIntegration,
  // Default browser integrations
  breadcrumbsIntegration,
  browserApiErrorsIntegration,
  browserSessionIntegration,
  cultureContextIntegration,
  globalHandlersIntegration,
  httpContextIntegration,
  linkedErrorsIntegration,
  // Transport / parsing
  defaultStackLineParsers,
  defaultStackParser,
  chromeStackLineParser,
  geckoStackLineParser,
  opera10StackLineParser,
  opera11StackLineParser,
  winjsStackLineParser,
  makeFetchTransport,
  // Scope helpers
  metrics,
  onLoad,
  parameterize,
  Scope,
  SDK_VERSION,
  SEMANTIC_ATTRIBUTE_SENTRY_OP,
  SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN,
  SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE,
  SEMANTIC_ATTRIBUTE_SENTRY_SOURCE,
  setAttribute,
  setAttributes,
  setContext,
  setConversationId,
  setCurrentClient,
  setExtra,
  setExtras,
  setTag,
  setTags,
  setUser,
  showReportDialog,
  spanToBaggageHeader,
  spanToJSON,
  spanToTraceHeader,
  startSession,
  suppressTracing,
  updateSpanName,
  withIsolationScope,
  withScope,
  withStreamedSpan,
  WINDOW,
  lazyLoadIntegration,
  normalizeStringifyValue,
  // Tracing
  browserTracingIntegration,
  defaultRequestInstrumentationOptions,
  instrumentOutgoingRequests,
  isBotUserAgent,
  reportPageLoaded,
  setActiveSpanInBrowser,
  startBrowserTracingNavigationSpan,
  startBrowserTracingPageLoadSpan,
  bindScopeToEmitter,
  getActiveSpan,
  getRootSpan,
  getSpanDescendants,
  getSpanStatusFromHttpCode,
  registerSpanErrorInstrumentation,
  setHttpStatus,
  setMeasurement,
  startInactiveSpan,
  startNewTrace,
  startSpan,
  startSpanManual,
  withActiveSpan,
  // Filtering / enrichment
  thirdPartyErrorFilterIntegration,
  moduleMetadataIntegration,
  rewriteFramesIntegration,
  captureConsoleIntegration,
  extraErrorDataIntegration,
  consoleLoggingIntegration,
  logger,
  makeMultiplexedTransport,
  MULTIPLEXED_TRANSPORT_EXTRA_KEY,
} from '@sentry/browser/core';
