import {
  SENTRY_SEGMENT_NAME_SOURCE,
  HTTP_METHOD,
  HTTP_REQUEST_METHOD,
  HTTP_ROUTE,
} from '@sentry/conventions/attributes';
import type { Client, Span } from '@sentry/core';
import {
  getIsolationScope,
  getRootSpan,
  hasSpanStreamingEnabled,
  HTTP_SPAN_NAME_FALLBACK,
  SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN,
  spanToJSON,
} from '@sentry/core';
import { ATTR_NEXT_ROUTE, ATTR_NEXT_SPAN_NAME, ATTR_NEXT_SPAN_TYPE } from '../common/nextSpanAttributes';
import { addHeadersAsAttributes } from '../common/utils/addHeadersAsAttributes';
import { dropMiddlewareTunnelRequests } from '../common/utils/dropMiddlewareTunnelRequests';
import { createLiveRootSpanAdapter } from '../common/utils/liveRootSpanAdapter';
import { maybeForkIsolationScopeForRootSpan } from '../common/utils/forkIsolationScopeForRootSpan';
import { maybeEnhanceServerComponentSpanName } from '../common/utils/tracingUtils';
import { maybeStartCronCheckIn } from './vercelCronsMonitoring';
import { maybeEnrichQueueConsumerSpan, maybeEnrichQueueProducerSpan } from './vercelQueuesMonitoring';

/**
 * Handles the on span start event for Next.js spans.
 * This function is used to enhance the span with additional information such as the route, the method, the headers, etc.
 * It is called for every span that is started by Next.js.
 * @param span The span that is starting.
 * @param client The client the hook is registered on.
 */
export function handleOnSpanStart(span: Span, client: Client): void {
  const spanAttributes = spanToJSON(span).attributes;
  const rootSpan = getRootSpan(span);
  const rootSpanAttributes = spanToJSON(rootSpan).attributes;
  const isRootSpan = span === rootSpan;

  dropMiddlewareTunnelRequests(span, spanAttributes);

  // Next.js names the incoming-request span after the raw URL. With span streaming, span names have to
  // be low cardinality, so we replace it here at span start; the `next.route` hoisting below renames it
  // to `${method} ${route}` once Next.js reports a route.
  if (
    isRootSpan &&
    spanAttributes?.[ATTR_NEXT_SPAN_TYPE] === 'BaseServer.handleRequest' &&
    hasSpanStreamingEnabled(client)
  ) {
    // eslint-disable-next-line typescript/no-deprecated
    const method = spanAttributes[HTTP_REQUEST_METHOD] ?? spanAttributes[HTTP_METHOD];
    createLiveRootSpanAdapter(span).setName(
      (typeof method === 'string' ? method.toUpperCase() : '') || HTTP_SPAN_NAME_FALLBACK,
    );
  }

  // What we do in this glorious piece of code, is hoist any information about parameterized routes from spans emitted
  // by Next.js via the `next.route` attribute, up to the transaction by setting the http.route attribute.
  if (typeof spanAttributes?.[ATTR_NEXT_ROUTE] === 'string') {
    // Only hoist the http.route attribute if the transaction doesn't already have it
    if (
      // eslint-disable-next-line typescript/no-deprecated
      (rootSpanAttributes?.[HTTP_REQUEST_METHOD] || rootSpanAttributes?.[HTTP_METHOD]) &&
      !rootSpanAttributes?.[HTTP_ROUTE]
    ) {
      const route = spanAttributes[ATTR_NEXT_ROUTE].replace(/\/route$/, '');
      // eslint-disable-next-line typescript/no-deprecated
      const method = rootSpanAttributes?.[HTTP_REQUEST_METHOD] || rootSpanAttributes?.[HTTP_METHOD];

      const name = typeof method === 'string' ? `${method} ${route}` : route;
      rootSpan.updateName(name);
      rootSpan.setAttributes({
        [HTTP_ROUTE]: route,
        // Preserving the original attribute despite internally not depending on it
        [ATTR_NEXT_ROUTE]: route,
        [SENTRY_SEGMENT_NAME_SOURCE]: 'route',
      });

      // Update the isolation scope's transaction name so that non-transaction events
      // (e.g. captureMessage, captureException) also get the parameterized route.
      getIsolationScope().setTransactionName(name);

      // Check if this is a Vercel cron request and start a check-in
      maybeStartCronCheckIn(rootSpan, route);

      // Enrich queue consumer spans (Vercel Queue push delivery via CloudEvent)
      maybeEnrichQueueConsumerSpan(rootSpan);
    }
  }

  if (spanAttributes?.[ATTR_NEXT_SPAN_TYPE] === 'Middleware.execute') {
    const middlewareName = spanAttributes[ATTR_NEXT_SPAN_NAME];
    if (typeof middlewareName === 'string') {
      rootSpan.updateName(middlewareName);
      rootSpan.setAttributes({
        [HTTP_ROUTE]: middlewareName,
        [ATTR_NEXT_SPAN_NAME]: middlewareName,
        [SENTRY_SEGMENT_NAME_SOURCE]: 'route',
      });
    }
    span.setAttribute(SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN, 'auto');
  }

  // We want to skip span data inference for any spans generated by Next.js. Reason being that Next.js emits spans
  // with patterns (e.g. http.server spans) that will produce confusing data.
  if (spanAttributes?.[ATTR_NEXT_SPAN_TYPE] !== undefined) {
    span.setAttribute(SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN, 'auto');
  }

  if (isRootSpan) {
    const headers = getIsolationScope().getScopeData().sdkProcessingMetadata?.normalizedRequest?.headers;
    addHeadersAsAttributes(headers, rootSpan);
  }

  maybeForkIsolationScopeForRootSpan(span, spanAttributes);

  maybeEnhanceServerComponentSpanName(span, spanAttributes, rootSpanAttributes);

  // Enrich outgoing http.client spans targeting the Vercel Queues API (producer)
  maybeEnrichQueueProducerSpan(span);
}
