import { describe, expect, it } from 'vitest';
import { matchUrlToRoutePattern } from '../../src/server/routeParametrization';

describe('matchUrlToRoutePattern', () => {
  const patterns = ['/users/$userId/posts/$postId', '/api/health', '/page-a', '/page-b/$id', '/'];

  it('matches the root route', () => {
    expect(matchUrlToRoutePattern('/', patterns)).toBe('/');
  });

  it('matches a static route', () => {
    expect(matchUrlToRoutePattern('/page-a', patterns)).toBe('/page-a');
  });

  it('matches a single-param route', () => {
    expect(matchUrlToRoutePattern('/page-b/42', patterns)).toBe('/page-b/$id');
  });

  it('matches a multi-param route', () => {
    expect(matchUrlToRoutePattern('/users/123/posts/456', patterns)).toBe('/users/$userId/posts/$postId');
  });

  it('returns undefined for unmatched paths', () => {
    expect(matchUrlToRoutePattern('/unknown', patterns)).toBeUndefined();
  });

  it('returns undefined for partially matched paths', () => {
    expect(matchUrlToRoutePattern('/page-b', patterns)).toBeUndefined();
  });

  it('prefers static over dynamic matches', () => {
    const patternsWithOverlap = ['/page-b/$id', '/page-b/special'];
    expect(matchUrlToRoutePattern('/page-b/special', patternsWithOverlap)).toBe('/page-b/special');
  });

  it('prefers more specific routes', () => {
    const patternsNested = ['/users/$id', '/users/$id/profile'];
    expect(matchUrlToRoutePattern('/users/123/profile', patternsNested)).toBe('/users/$id/profile');
  });

  it('handles URLs with trailing slashes', () => {
    expect(matchUrlToRoutePattern('/page-a/', patterns)).toBe('/page-a');
    expect(matchUrlToRoutePattern('/page-b/42/', patterns)).toBe('/page-b/$id');
  });

  describe('TanStack Router segment grammar', () => {
    // `fullPaths` of a route tree generated by @tanstack/router-generator, in generator order.
    // Expected matches were checked against `router.matchRoutes()` of @tanstack/react-router.
    const routeTreePatterns = [
      '/',
      '/$user',
      '/@{$groupSlug}',
      '/about',
      '/blog/latest',
      '/blog/{-$tag}',
      '/files',
      '/posts',
      '/pre-{$id}-post',
      '/shop/items',
      '/sitemap-{$page}.xml',
      '/dashboard',
      '/docs/',
      '/docs/{$}',
      '/files/$',
      '/files/special',
      '/groups/$groupId',
      '/posts/$postId',
      '/{-$locale}/about',
      '/artists/',
      '/@{$groupSlug}/covers/$coverId',
      '/a/$x/c',
      '/a/b/$y',
      '/shop/{-$cat}/items',
      '/groups/$groupId/',
    ];

    it.each([
      ['/', '/'],
      ['/artists', '/artists/'],
      ['/artists/', '/artists/'],
      ['/ARTISTS', '/artists/'],
      ['/groups/abc', '/groups/$groupId/'],
      ['/groups/abc/', '/groups/$groupId/'],
      ['/@some-group', '/@{$groupSlug}'],
      ['/@some-group/covers/c1', '/@{$groupSlug}/covers/$coverId'],
      ['/sitemap-3.xml', '/sitemap-{$page}.xml'],
      ['/sitemap-.xml', '/sitemap-{$page}.xml'],
      ['/pre-1-post', '/pre-{$id}-post'],
      ['/about', '/{-$locale}/about'],
      ['/en/about', '/{-$locale}/about'],
      ['/shop/items', '/shop/{-$cat}/items'],
      ['/shop/toys/items', '/shop/{-$cat}/items'],
      ['/blog/latest', '/blog/latest'],
      ['/blog/foo', '/blog/{-$tag}'],
      ['/files', '/files/$'],
      ['/files/a/b/c', '/files/$'],
      ['/files/special', '/files/special'],
      ['/docs', '/docs/'],
      ['/docs/x/y', '/docs/{$}'],
      ['/a/b/c', '/a/b/$y'],
      ['/a/z/c', '/a/$x/c'],
      ['/john', '/$user'],
      ['/posts/1', '/posts/$postId'],
      ['/dashboard', '/dashboard'],
    ])('matches %s to %s', (pathname, expected) => {
      expect(matchUrlToRoutePattern(pathname, routeTreePatterns)).toBe(expected);
    });

    it('does not match paths no route covers', () => {
      expect(matchUrlToRoutePattern('/nope/nope/nope', routeTreePatterns)).toBeUndefined();
    });
  });
});
