// @ts-check

/**
 * Rollup config docs: https://rollupjs.org/guide/en/#big-list-of-options
 */

import * as fs from 'fs';
import { builtinModules } from 'module';
import * as path from 'path';
import { fileURLToPath } from 'url';

import deepMerge from 'deepmerge';

import { defineConfig } from 'rollup';
import {
  makeDebugBuildStatementReplacePlugin,
  makeEsbuildPlugin,
  makeEsmCjsReplacePlugin,
  makeNodeResolvePlugin,
  makeProductionReplacePlugin,
  makeRrwebBuildPlugin,
} from './plugins/index.mjs';
import { makePackageNodeEsm } from './plugins/make-esm-plugin.mjs';
import { mergeExternals, mergePlugins } from './utils.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const packageDotJSON = JSON.parse(fs.readFileSync(path.resolve(process.cwd(), './package.json'), { encoding: 'utf8' }));

const ignoreSideEffects = /[\\/]debug-build\.ts$/;

const repoRoot = path.resolve(__dirname, '../..');
const sideEffectsCache = new Map();

/**
 * Whether an external package declares `"sideEffects": false` in its `package.json`.
 * Unknown packages are treated as having side effects.
 */
function isSideEffectFreePackage(packageName) {
  const cached = sideEffectsCache.get(packageName);
  if (cached !== undefined) {
    return cached;
  }

  let sideEffectFree = false;
  try {
    const json = JSON.parse(
      fs.readFileSync(path.resolve(repoRoot, 'node_modules', packageName, 'package.json'), { encoding: 'utf8' }),
    );
    sideEffectFree = json.sideEffects === false;
  } catch {
    // Not resolvable from the repo root - assume side effects.
  }

  sideEffectsCache.set(packageName, sideEffectFree);
  return sideEffectFree;
}

function getPackageName(id) {
  const segments = id.split('/');
  return id.startsWith('@') ? segments.slice(0, 2).join('/') : segments[0];
}

export function makeBaseNPMConfig(options = {}) {
  const {
    entrypoints = ['src/index.ts'],
    hasBundles = false,
    packageSpecificConfig = {},
    esbuild = {},
    bundledBuiltins = [],
  } = options;

  const nodeResolvePlugin = makeNodeResolvePlugin();
  const transpilePlugin = makeEsbuildPlugin(esbuild);
  const debugBuildStatementReplacePlugin = makeDebugBuildStatementReplacePlugin();
  const rrwebBuildPlugin = makeRrwebBuildPlugin({
    excludeShadowDom: undefined,
    excludeIframe: undefined,
  });

  const deps = [
    ...builtinModules.filter(m => !bundledBuiltins.includes(m)),
    ...Object.keys(packageDotJSON.dependencies || {}),
    ...Object.keys(packageDotJSON.peerDependencies || {}),
    ...Object.keys(packageDotJSON.optionalDependencies || {}),
  ];

  const defaultBaseConfig = {
    input: entrypoints,

    output: {
      // an appropriately-named directory will be added to this base value when we specify either a cjs or esm build
      dir: hasBundles ? 'build/npm' : 'build',

      sourcemap: true,

      // Include __esModule property when there is a default prop
      esModule: 'if-default-prop',

      // output individual files rather than one big bundle
      preserveModules: true,

      // Don't hoist imports into entrypoints
      // should be ignored when `preserveModules` is used,
      // but Rollup still includes them when hoisting transitive imports.
      hoistTransitiveImports: false,

      // Allow wrappers or helper functions generated by rollup to use any ES2015 features
      generatedCode: {
        preset: 'es2015',
      },

      // don't add `"use strict"` to the top of cjs files
      strict: false,

      // Use simple exports format:
      //     exports.dogs = are.great
      // rather than Object.defineProperty style exports:
      //     Object.defineProperty(exports, 'dogs', {
      //       enumerable: true,
      //       get: () => are.great,
      //     });
      externalLiveBindings: false,

      // Don't call `Object.freeze` on the results of `import * as someModule from '...'`
      // (We don't need it, so why waste the bytes?)
      freeze: false,

      // Assume externals are ESM-shaped (`__esModule` + `.default`), which our own `@sentry/*`
      // packages satisfy via `esModule: 'if-default-prop'`. This keeps `import * as x` a live
      // reference to the real module rather than an `_interopNamespace` copy — instrumentation code
      // relies on that to monkey-patch modules like `fs` in place. Packages that pull in bare-CJS
      // third-party deps (no `.default`) override this per-module (see server-utils).
      interop: 'esModule',
    },

    treeshake: {
      moduleSideEffects: (id, external) => {
        if (external === false && ignoreSideEffects.test(id)) {
          // Tell Rollup this module has no side effects, so it can be tree-shaken
          return false;
        }

        // Rollup keeps a bare `import '<pkg>'` alive whenever it tree-shakes away every
        // binding of an external it believes has side effects. For a package that declares
        // `"sideEffects": false` that import contradicts its own manifest, and bundlers such
        // as esbuild warn about it (`ignored-bare-import`).
        if (external && isSideEffectFreePackage(getPackageName(id))) {
          return false;
        }

        return true;
      },
    },

    plugins: [nodeResolvePlugin, transpilePlugin, debugBuildStatementReplacePlugin, rrwebBuildPlugin],

    // don't include imported modules from outside the package in the final output
    // also treat subpath exports (e.g. `@sentry/core/browser`) as external
    external: id => {
      // treat subpath exports as external if the package is external
      return deps.some(dep => id === dep || id.startsWith(`${dep}/`));
    },
  };

  return deepMerge(defaultBaseConfig, packageSpecificConfig, {
    // Plugins have to be in the correct order or everything breaks, so when merging we have to manually re-order them
    customMerge: key => {
      if (key === 'plugins') return mergePlugins;
      if (key === 'external') return mergeExternals;
      return undefined;
    },
  });
}

export function makeNPMConfigVariants(baseConfig, options = {}) {
  const { emitEsm = true, emitCjs = true, splitDevProd = false } = options;

  const variantSpecificConfigs = [];

  if (emitCjs) {
    if (splitDevProd) {
      variantSpecificConfigs.push({
        output: { format: 'cjs', dir: path.join(baseConfig.output.dir, 'cjs/dev') },
        plugins: [makeEsmCjsReplacePlugin('cjs')],
      });
      variantSpecificConfigs.push({
        output: { format: 'cjs', dir: path.join(baseConfig.output.dir, 'cjs/prod') },
        plugins: [makeProductionReplacePlugin(), makeEsmCjsReplacePlugin('cjs')],
      });
    } else {
      variantSpecificConfigs.push({
        output: { format: 'cjs', dir: path.join(baseConfig.output.dir, 'cjs') },
        plugins: [makeEsmCjsReplacePlugin('cjs')],
      });
    }
  }

  if (emitEsm) {
    if (splitDevProd) {
      variantSpecificConfigs.push({
        output: { format: 'esm', dir: path.join(baseConfig.output.dir, 'esm/dev') },
        plugins: [makePackageNodeEsm(), makeEsmCjsReplacePlugin('esm')],
      });
      variantSpecificConfigs.push({
        output: { format: 'esm', dir: path.join(baseConfig.output.dir, 'esm/prod') },
        plugins: [makePackageNodeEsm(), makeProductionReplacePlugin(), makeEsmCjsReplacePlugin('esm')],
      });
    } else {
      variantSpecificConfigs.push({
        output: { format: 'esm', dir: path.join(baseConfig.output.dir, 'esm') },
        plugins: [makePackageNodeEsm(), makeEsmCjsReplacePlugin('esm')],
      });
    }
  }

  return variantSpecificConfigs.map(variant =>
    // Plugin arrays must be merged in the right order or the build silently misbehaves
    // (e.g. esbuild strips dev-mode marker comments before the replace plugin can act).
    deepMerge(baseConfig, variant, {
      customMerge: key => (key === 'plugins' ? mergePlugins : undefined),
    }),
  );
}

/**
 * Emits the `@sentry/<framework>/import` entry (`build/import-hook.mjs`) as part of the rollup build,
 * used as `node --import @sentry/<framework>/import app.js`. The generated hook imports
 * `@sentry/server-utils/orchestrion/import-hook`, which registers the orchestrion
 * diagnostics-channel injection, so the consuming package must declare `@sentry/server-utils` as a
 * dependency.
 *
 * @param {string} outputFolder Build output folder.
 */
export function makeOrchestrionLoader(outputFolder) {
  const expectedImportHookLocation = `${outputFolder}/import-hook.mjs`;
  const foundImportHookExport = Object.keys(packageDotJSON.exports ?? {}).some(key => {
    return packageDotJSON?.exports?.[key]?.import?.default === expectedImportHookLocation;
  });
  if (!foundImportHookExport) {
    throw new Error(
      `You used the makeOrchestrionLoader() rollup utility without specifying the import hook inside \`exports[something].import.default\`. Please add "${expectedImportHookLocation}" as a value there (maybe check for typos - it needs to be "${expectedImportHookLocation}" exactly).`,
    );
  }

  const requiredDep = '@sentry/server-utils';
  const foundRequiredDep =
    Object.keys(packageDotJSON.dependencies ?? {}).some(key => {
      return key === requiredDep;
    }) ||
    Object.keys(packageDotJSON.devDependencies ?? {}).some(key => {
      return key === requiredDep;
    });

  if (!foundRequiredDep) {
    throw new Error(
      `You used the makeOrchestrionLoader() rollup utility but didn't specify the "${requiredDep}" dependency in ${path.resolve(
        process.cwd(),
        'package.json',
      )}. Please add it to the dependencies.`,
    );
  }

  return defineConfig([
    {
      input: path.join(__dirname, 'code', 'importHookTemplate.js'),
      external: /.*/,
      output: {
        format: 'esm',
        file: path.join(outputFolder, 'import-hook.mjs'),
      },
    },
  ]);
}
