/* This file was generated by './scripts/generate-plugin-combinations.js'! */
const Raven = require('../../src/singleton');
const angularPlugin = require('../angular');
const consolePlugin = require('../console');
const requirePlugin = require('../require');

Raven
  .addPlugin(angularPlugin)
  .addPlugin(consolePlugin)
  .addPlugin(requirePlugin);
