/* This file was generated by './scripts/generate-plugin-combinations.js'! */
const Raven = require('../../src/singleton');
const angularPlugin = require('../angular');
const emberPlugin = require('../ember');

Raven
  .addPlugin(angularPlugin)
  .addPlugin(emberPlugin);
