/* This file was generated by './scripts/generate-plugin-combinations.js'! */
const Raven = require('../../src/singleton');
const consolePlugin = require('../console');
const vuePlugin = require('../vue');

Raven
  .addPlugin(consolePlugin)
  .addPlugin(vuePlugin);
