/* This file was generated by './scripts/generate-plugin-combinations.js'! */
const Raven = require('../../src/singleton');
const requirePlugin = require('../require');
const vuePlugin = require('../vue');

Raven
  .addPlugin(requirePlugin)
  .addPlugin(vuePlugin);
