/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: c05b8abbf6467bf68c4367b2d4797256)
interface __BaseEnv_Env {
  E2E_TEST_DSN: string;
  MY_DURABLE_OBJECT: DurableObjectNamespace<import('./src/index').MyDurableObject>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
    durableNamespaces: 'MyDurableObject';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
