/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2e45ec7e84d4165c887897853de803b3)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./sentry.server.config');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
