import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';
import { sentryPagesPlugin } from '@sentry/cloudflare';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from '../build/server';

export const onRequest = [
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (context: any) => sentryPagesPlugin({ dsn: context.env.E2E_TEST_DSN })(context),
  createPagesFunctionHandler({ build }),
];
