import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input
          type="button"
          value="Capture Exception"
          id="exception-button"
          onClick={() => {
            throw new Error('I am an error!');
          }}
        />
        <Link href="/user/5" id="navigation">
          navigate
        </Link>
      </main>
    </>
  );
}
