/**
 * Where an error passed to `handleError` came from. Added in SvelteKit 3; `undefined` on
 * SvelteKit 1.x and 2.x.
 *
 * - `app`: thrown with the `error(...)` helper
 * - `framework`: generated by SvelteKit itself (404s, 405s, 413s, ...)
 * - `validation`: invalid remote function arguments (server only)
 * - `unknown`: thrown by user code, or code it calls
 *
 * @see https://svelte.dev/docs/kit/hooks#handleError
 */
export type CaughtErrorKind = 'app' | 'framework' | 'validation' | 'unknown';

/**
 * The input of a SvelteKit `handleError` hook, covering SvelteKit 1.x, 2.x and 3.
 *
 * We declare this structurally instead of importing SvelteKit's `HandleServerError`/
 * `HandleClientError`, because those types moved from `@sveltejs/kit` to `@sveltejs/kit/hooks`
 * in SvelteKit 3 and neither import path type-checks against both majors.
 */
export type SentryHandleErrorInput = {
  error: unknown;

  /** SvelteKit 3+ only */
  kind?: CaughtErrorKind;

  /** SvelteKit 3+, and only for `kind: 'validation'` */
  issues?: unknown[];

  /**
   * SvelteKit 1.x and 2.x only — SvelteKit 3 moved the status onto the error itself.
   * Careful: in SvelteKit 3 dev builds this still exists as a deprecated getter that logs a
   * warning when read, so only access it when `kind` is absent.
   */
  status?: number;

  /**
   * SvelteKit 1.x and 2.x only. Same deprecation caveat as {@link SentryHandleErrorInput.status}.
   */
  message?: string;
};

/** The `handleError` input on the server, where we also read from the request event. */
export type SentryHandleServerErrorInput = SentryHandleErrorInput & {
  event: {
    route?: { id?: string | null };
    platform?: unknown;
  };
};

/** The `handleError` input on the client. */
export type SentryHandleClientErrorInput = SentryHandleErrorInput & {
  event: unknown;
};

/**
 * Constrains the user-provided `handleError` hook without depending on SvelteKit's own types.
 * `never` as the parameter type accepts any single-argument function (parameters are
 * contravariant), so a SvelteKit 1.x, 2.x or 3 hook all satisfy it.
 */
export type AnyErrorHandler = (input: never) => unknown;

/**
 * Reads the HTTP status off an error. In SvelteKit 3, `app`, `framework` and `validation` errors
 * all carry their status here.
 */
export function getErrorStatus(error: unknown): number | undefined {
  if (error == null || typeof error !== 'object') {
    return undefined;
  }

  const { status } = error as { status?: unknown };

  return typeof status === 'number' ? status : undefined;
}

/**
 * Whether an error passed to `handleError` should be sent to Sentry.
 *
 * Only relevant for SvelteKit 3+, where every error reaches `handleError` — including expected
 * ones thrown with `error(...)` and framework errors like 404s, neither of which showed up here
 * on SvelteKit 2. We apply the same rule the rest of the SDK uses for thrown `HttpError`s
 * (see `sendErrorToSentry`): 4xx are expected and noisy, 5xx are worth reporting.
 *
 * @returns `undefined` if the input isn't a SvelteKit 3 one, so callers can apply their own
 * version-specific logic.
 */
export function shouldCaptureCaughtError(input: SentryHandleErrorInput): boolean | undefined {
  if (!input.kind) {
    return undefined;
  }

  // Unexpected errors have no status of their own; SvelteKit reports them as 500s.
  if (input.kind === 'unknown') {
    return true;
  }

  const status = getErrorStatus(input.error);

  // If we can't tell, err on the side of capturing.
  return status === undefined || status >= 500;
}
