/* This file was generated by './scripts/generate-plugin-combinations.js'! */
const Raven = require('../../src/singleton');
const requirePlugin = require('../require');

Raven
  .addPlugin(requirePlugin);
