name: Build Playwright Docker Image
on:
  push:
    branches: [develop]
    paths:
      - '.github/docker/playwright.Dockerfile'
      - 'dev-packages/browser-integration-tests/package.json'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Get Playwright version
        id: playwright
        run: echo "version=$(node -p "require('./dev-packages/browser-integration-tests/package.json').devDependencies['@playwright/test'].replace('~', '')")" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: .github/docker/playwright.Dockerfile
          push: true
          build-args: |
            PLAYWRIGHT_VERSION=${{ steps.playwright.outputs.version }}
          tags: |
            ghcr.io/${{ github.repository }}/playwright:v${{ steps.playwright.outputs.version }}
